name: Build

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'docs/**'  # Ignore changes only within the docs directory
  workflow_dispatch:

permissions: write-all

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          token: ${{secrets.WORKFLOW_TOKEN}}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'
          cache: 'npm'
      - run: npm ci --include=optional
      - uses: nrwl/nx-set-shas@v4
      - name: Checkout release branch or create it
        run: |
          git fetch origin
          git checkout release || git checkout -b release origin/main
          git reset --hard origin/main
      - run: | 
          rm -rf docs
          #npx nx-cloud record -- nx format:write
          #npx nx-cloud record -- nx run-many -t lint --fix
          npx nx run-many --target=build --all --outputPath=docs
      - run: |
          git config user.email "keaackerman@gmail.com"
          git config user.name "Kaisa Ackerman"
          git add .
          git commit -m "Automatic build" -a || echo "No changes to commit"
          git push --force origin release
          git checkout main
          git merge release --no-edit
          git push origin main