name: Validation

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'dist/**' # Ignore changes only within the docs directory
      - 'docs/**' # Ignore changes only within the docs directory
  workflow_dispatch:

permissions: read-all

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'
          cache: 'npm'
      - run: npm ci --include=optional
      - run: npx nx affected --target=format:check
      - run: npx nx affected --target=lint --parallel
      - run: npx nx affected --target=test --parallel
      - run: npx nx affected --target=build --parallel
      - run: npx nx affected --target=e2e-ci
